### ISSUE TITLE
Use Quarkus

### ISSUE THREAD

**Issue by jesuino** [IuryAlves/passar-raiva-com-java-todo-dia-que-alegria#1]
Use quarkus que é melhor :-) 
Se tiver problemas o desenvolvimento está muito ativo, vai passar menos raiva, se achar bug dá pra arrumar fix

Desenvolver com quarkus é uma delícia, compila para app nativa e vc coloca no kubernetes

**Comment by IuryAlves** [comment]
Eu preciso testar um código em groovy na verdade.

Mockito e Powermock tem certas limitações.

Eu não consigo mockar `new Class()` por exemplo
